using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PAYPAL.RandomData
{
    public class Second_Words_95
    {
        public List<string> Get_95_Second_Words_List() 
        { 
            List<string> second_words_95 = new List<string>();
            string word_01 = "tin";
            string word_02 = "dou";
            string word_03 = "jimmy";
            string word_04 = "khang";
            string word_05 = "lvy";
            string word_06 = "nhat";
            string word_07 = "jewel";
            string word_08 = "thang";
            string word_09 = "nam";
            string word_10 = "the";
            string word_11 = "loan";
            string word_12 = "huynh";
            string word_13 = "manh";
            string word_14 = "quy";
            string word_15 = "phung";
            string word_16 = "art";
            string word_17 = "dung";
            string word_18 = "luan";
            string word_19 = "ann";
            string word_20 = "lang";
            string word_21 = "thai";
            string word_22 = "vinh";
            string word_23 = "aqua";
            string word_24 = "huy";
            string word_25 = "thy";
            string word_26 = "beef";
            string word_27 = "ton";
            string word_28 = "thuan";
            string word_29 = "anh";
            string word_30 = "tat";
            string word_31 = "boss";
            string word_32 = "khanh";
            string word_33 = "thi";
            string word_34 = "cong";
            string word_35 = "dien";
            string word_36 = "old";
            string word_37 = "mau";
            string word_38 = "toan";
            string word_39 = "lus";
            string word_40 = "nero";
            string word_41 = "hien";
            string word_42 = "cao";
            string word_43 = "huong";
            string word_44 = "ziall";
            string word_45 = "lam";
            string word_46 = "dat";
            string word_47 = "nhuan";
            string word_48 = "khuu";
            string word_49 = "nghi";
            string word_50 = "nghia";
            string word_51 = "mark";
            string word_52 = "ali";
            string word_53 = "gia";
            string word_54 = "dino";
            string word_55 = "yaly";
            string word_56 = "vuong";
            string word_57 = "tuyen";
            string word_58 = "bao";
            string word_59 = "zeus";
            string word_60 = "liem";
            string word_61 = "ngan";
            string word_62 = "light";
            string word_63 = "trieu";
            string word_64 = "hau";
            string word_65 = "eco";
            string word_66 = "llii";
            string word_67 = "chen";
            string word_68 = "angel";
            string word_69 = "kath";
            string word_70 = "chau";
            string word_71 = "world";
            string word_72 = "loc";
            string word_73 = "love";
            string word_74 = "sage";
            string word_75 = "tri";
            string word_76 = "con";
            string word_77 = "field";
            string word_78 = "lee";
            string word_79 = "son";
            string word_80 = "dieu";
            string word_81 = "dance";
            string word_82 = "hanh";
            string word_83 = "trien";
            string word_84 = "thuc";
            string word_85 = "jony";
            string word_86 = "nhi";
            string word_87 = "yen";
            string word_88 = "ven";
            string word_89 = "tinh";
            string word_90 = "kien";
            string word_91 = "dong";
            string word_92 = "hoan";
            string word_93 = "nhan";
            string word_94 = "you";
            string word_95 = "hiep";

            //Add vào list
            second_words_95.Add(word_01);
            second_words_95.Add(word_02);
            second_words_95.Add(word_03);
            second_words_95.Add(word_04);
            second_words_95.Add(word_05);
            second_words_95.Add(word_06);
            second_words_95.Add(word_07);
            second_words_95.Add(word_08);
            second_words_95.Add(word_09);
            second_words_95.Add(word_10);
            second_words_95.Add(word_11);
            second_words_95.Add(word_12);
            second_words_95.Add(word_13);
            second_words_95.Add(word_14);
            second_words_95.Add(word_15);
            second_words_95.Add(word_16);
            second_words_95.Add(word_17);
            second_words_95.Add(word_18);
            second_words_95.Add(word_19);
            second_words_95.Add(word_20);
            second_words_95.Add(word_21);
            second_words_95.Add(word_22);
            second_words_95.Add(word_23);
            second_words_95.Add(word_24);
            second_words_95.Add(word_25);
            second_words_95.Add(word_26);
            second_words_95.Add(word_27);
            second_words_95.Add(word_28);
            second_words_95.Add(word_29);
            second_words_95.Add(word_30);
            second_words_95.Add(word_31);
            second_words_95.Add(word_32);
            second_words_95.Add(word_33);
            second_words_95.Add(word_34);
            second_words_95.Add(word_35);
            second_words_95.Add(word_36);
            second_words_95.Add(word_37);
            second_words_95.Add(word_38);
            second_words_95.Add(word_39);
            second_words_95.Add(word_40);
            second_words_95.Add(word_41);
            second_words_95.Add(word_42);
            second_words_95.Add(word_43);
            second_words_95.Add(word_44);
            second_words_95.Add(word_45);
            second_words_95.Add(word_46);
            second_words_95.Add(word_47);
            second_words_95.Add(word_48);
            second_words_95.Add(word_49);
            second_words_95.Add(word_50);
            second_words_95.Add(word_51);
            second_words_95.Add(word_52);
            second_words_95.Add(word_53);
            second_words_95.Add(word_54);
            second_words_95.Add(word_55);
            second_words_95.Add(word_56);
            second_words_95.Add(word_57);
            second_words_95.Add(word_58);
            second_words_95.Add(word_59);
            second_words_95.Add(word_60);
            second_words_95.Add(word_61);
            second_words_95.Add(word_62);
            second_words_95.Add(word_63);
            second_words_95.Add(word_64);
            second_words_95.Add(word_65);
            second_words_95.Add(word_66);
            second_words_95.Add(word_67);
            second_words_95.Add(word_68);
            second_words_95.Add(word_69);
            second_words_95.Add(word_70);
            second_words_95.Add(word_71);
            second_words_95.Add(word_72);
            second_words_95.Add(word_73);
            second_words_95.Add(word_74);
            second_words_95.Add(word_75);
            second_words_95.Add(word_76);
            second_words_95.Add(word_77);
            second_words_95.Add(word_78);
            second_words_95.Add(word_79);
            second_words_95.Add(word_80);
            second_words_95.Add(word_81);
            second_words_95.Add(word_82);
            second_words_95.Add(word_83);
            second_words_95.Add(word_84);
            second_words_95.Add(word_85);
            second_words_95.Add(word_86);
            second_words_95.Add(word_87);
            second_words_95.Add(word_88);
            second_words_95.Add(word_89);
            second_words_95.Add(word_90);
            second_words_95.Add(word_91);
            second_words_95.Add(word_92);
            second_words_95.Add(word_93);
            second_words_95.Add(word_94);
            second_words_95.Add(word_95);

            return second_words_95;
        }
    }
}
