using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PAYPAL.RandomData
{
    public class Upper_First_Letter_Words_96
    {
        public List<string> Get_96_First_Words_List() 
        { 
            List<string> first_words_96 = new List<string>();

            string word_01 = "Tai";
            string word_02 = "Duong";
            string word_03 = "Kha";
            string word_04 = "Duy";
            string word_05 = "Chu";
            string word_06 = "Pham";
            string word_07 = "Tran";
            string word_08 = "Khoa";
            string word_09 = "Phan";
            string word_10 = "Duc";
            string word_11 = "Luong";
            string word_12 = "Quan";
            string word_13 = "Mr.";
            string word_14 = "Tang";
            string word_15 = "Quyen";
            string word_16 = "Phuc";
            string word_17 = "His";
            string word_18 = "Quynh";
            string word_19 = "Dang";
            string word_20 = "Ngoc";
            string word_21 = "Tien";
            string word_22 = "Quoc";
            string word_23 = "Dai";
            string word_24 = "Long";
            string word_25 = "Phong";
            string word_26 = "Hung";
            string word_27 = "Xuan";
            string word_28 = "Big";
            string word_29 = "Dam";
            string word_30 = "Bui";
            string word_31 = "Sang";
            string word_32 = "Phuoc";
            string word_33 = "Mpt";
            string word_34 = "Chi";
            string word_35 = "Viet";
            string word_36 = "Ngo";
            string word_37 = "Tina";
            string word_38 = "Kenny";
            string word_39 = "Hoang";
            string word_40 = "Doan";
            string word_41 = "Jolie";
            string word_42 = "Hong";
            string word_43 = "Trinh";
            string word_44 = "Trung";
            string word_45 = "Table";
            string word_46 = "Tevin";
            string word_47 = "Hoa";
            string word_48 = "Nha";
            string word_49 = "Tram";
            string word_50 = "Nga";
            string word_51 = "Alex";
            string word_52 = "Thu";
            string word_53 = "Trang";
            string word_54 = "Nick";
            string word_55 = "Hieu";
            string word_56 = "Write";
            string word_57 = "Brian";
            string word_58 = "Tuan";
            string word_59 = "Tan";
            string word_60 = "Alan";
            string word_61 = "Khac";
            string word_62 = "Minh";
            string word_63 = "Ben";
            string word_64 = "Quang";
            string word_65 = "Black";
            string word_66 = "Duly";
            string word_67 = "Tung";
            string word_68 = "Danh";
            string word_69 = "Lucky";
            string word_70 = "Uyen";
            string word_71 = "Cuong";
            string word_72 = "Dao";
            string word_73 = "Thong";
            string word_74 = "Diep";
            string word_75 = "Lan";
            string word_76 = "Huu";
            string word_77 = "Trong";
            string word_78 = "Linh";
            string word_79 = "Thao";
            string word_80 = "Mai";
            string word_81 = "Win";
            string word_82 = "Bon";
            string word_83 = "Dinh";
            string word_84 = "Hai";
            string word_85 = "Zeno";
            string word_86 = "Nong";
            string word_87 = "Kieu";
            string word_88 = "Arrow";
            string word_89 = "Lake";
            string word_90 = "Van";
            string word_91 = "Hoai";
            string word_92 = "Max";
            string word_93 = "Japan";
            string word_94 = "Thuy";
            string word_95 = "Thanh";
            string word_96 = "Kaito";

            //Add vào list

            first_words_96.Add(word_01);
            first_words_96.Add(word_02);
            first_words_96.Add(word_03);
            first_words_96.Add(word_04);
            first_words_96.Add(word_05);
            first_words_96.Add(word_06);
            first_words_96.Add(word_07);
            first_words_96.Add(word_08);
            first_words_96.Add(word_09);
            first_words_96.Add(word_10);
            first_words_96.Add(word_11);
            first_words_96.Add(word_12);
            first_words_96.Add(word_13);
            first_words_96.Add(word_14);
            first_words_96.Add(word_15);
            first_words_96.Add(word_16);
            first_words_96.Add(word_17);
            first_words_96.Add(word_18);
            first_words_96.Add(word_19);
            first_words_96.Add(word_20);
            first_words_96.Add(word_21);
            first_words_96.Add(word_22);
            first_words_96.Add(word_23);
            first_words_96.Add(word_24);
            first_words_96.Add(word_25);
            first_words_96.Add(word_26);
            first_words_96.Add(word_27);
            first_words_96.Add(word_28);
            first_words_96.Add(word_29);
            first_words_96.Add(word_30);
            first_words_96.Add(word_31);
            first_words_96.Add(word_32);
            first_words_96.Add(word_33);
            first_words_96.Add(word_34);
            first_words_96.Add(word_35);
            first_words_96.Add(word_36);
            first_words_96.Add(word_37);
            first_words_96.Add(word_38);
            first_words_96.Add(word_39);
            first_words_96.Add(word_40);
            first_words_96.Add(word_41);
            first_words_96.Add(word_42);
            first_words_96.Add(word_43);
            first_words_96.Add(word_44);
            first_words_96.Add(word_45);
            first_words_96.Add(word_46);
            first_words_96.Add(word_47);
            first_words_96.Add(word_48);
            first_words_96.Add(word_49);
            first_words_96.Add(word_50);
            first_words_96.Add(word_51);
            first_words_96.Add(word_52);
            first_words_96.Add(word_53);
            first_words_96.Add(word_54);
            first_words_96.Add(word_55);
            first_words_96.Add(word_56);
            first_words_96.Add(word_57);
            first_words_96.Add(word_58);
            first_words_96.Add(word_59);
            first_words_96.Add(word_60);
            first_words_96.Add(word_61);
            first_words_96.Add(word_62);
            first_words_96.Add(word_63);
            first_words_96.Add(word_64);
            first_words_96.Add(word_65);
            first_words_96.Add(word_66);
            first_words_96.Add(word_67);
            first_words_96.Add(word_68);
            first_words_96.Add(word_69);
            first_words_96.Add(word_70);
            first_words_96.Add(word_71);
            first_words_96.Add(word_72);
            first_words_96.Add(word_73);
            first_words_96.Add(word_74);
            first_words_96.Add(word_75);
            first_words_96.Add(word_76);
            first_words_96.Add(word_77);
            first_words_96.Add(word_78);
            first_words_96.Add(word_79);
            first_words_96.Add(word_80);
            first_words_96.Add(word_81);
            first_words_96.Add(word_82);
            first_words_96.Add(word_83);
            first_words_96.Add(word_84);
            first_words_96.Add(word_85);
            first_words_96.Add(word_86);
            first_words_96.Add(word_87);
            first_words_96.Add(word_88);
            first_words_96.Add(word_89);
            first_words_96.Add(word_90);
            first_words_96.Add(word_91);
            first_words_96.Add(word_92);
            first_words_96.Add(word_93);
            first_words_96.Add(word_94);
            first_words_96.Add(word_95);
            first_words_96.Add(word_96);

            return first_words_96;

        }
    }
}
